src/Entity/User.php
<?php

/*
 * This file is part of the Kimai time-tracking app.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="kimai2_users",
 *      uniqueConstraints={
 *          @ORM\UniqueConstraint(columns={"username"}),
 *          @ORM\UniqueConstraint(columns={"email"})
 *      }
 * )
 * @UniqueEntity("username")
 * @UniqueEntity("email")
 */
class User extends BaseUser implements UserInterface
{
    public const ROLE_USER = 'ROLE_USER';
    public const ROLE_TEAMLEAD = 'ROLE_TEAMLEAD';
    public const ROLE_ADMIN = 'ROLE_ADMIN';
    public const ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN';

    public const DEFAULT_ROLE = self::ROLE_USER;
    public const DEFAULT_LANGUAGE = 'en';

    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(name="id", type="integer")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="alias", type="string", length=60, nullable=true)
     * @Assert\Length(max=160)
     */
    private $alias;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="registration_date", type="datetime", nullable=true)
     */
    private $registeredAt;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=50, nullable=true)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="avatar", type="string", length=255, nullable=true)
     */
    private $avatar;

    /**
     * @var string
     *
     * @ORM\Column(name="api_token", type="string", length=255, nullable=true)
     */
    protected $apiToken;

    /**
     * @var string
     */
    protected $plainApiToken;

    /**
     * @var UserPreference[]|Collection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\UserPreference", mappedBy="user", cascade={"persist"})
     */
    private $preferences;

    /**
     * @var Team[]|ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Team", inversedBy="users", cascade={"persist"})
     * @ORM\JoinTable(
     *  name="kimai2_users_teams",
     *  joinColumns={
     *      @ORM\JoinColumn(name="user_id", referencedColumnName="id", onDelete="CASCADE")
     *  },
     *  inverseJoinColumns={
     *      @ORM\JoinColumn(name="team_id", referencedColumnName="id", onDelete="CASCADE")
     *  }
     * )
     */
    private $teams;

    /**
     * User constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->registeredAt = new \DateTime();
        $this->preferences = new ArrayCollection();
        $this->teams = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRegisteredAt(): ?\DateTime
    {
        return $this->registeredAt;
    }

    public function setRegisteredAt(\DateTime $registeredAt): User
    {
        $this->registeredAt = $registeredAt;

        return $this;
    }

    public function setAlias(?string $alias): User
    {
        $this->alias = $alias;

        return $this;
    }

    public function getAlias(): ?string
    {
        return $this->alias;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): User
    {
        $this->title = $title;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): User
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getApiToken(): ?string
    {
        return $this->apiToken;
    }

    public function setApiToken(?string $apiToken): User
    {
        $this->apiToken = $apiToken;

        return $this;
    }

    public function getPlainApiToken(): ?string
    {
        return $this->plainApiToken;
    }

    public function setPlainApiToken(?string $plainApiToken): User
    {
        $this->plainApiToken = $plainApiToken;

        return $this;
    }

    /**
     * @return Collection<UserPreference>
     */
    public function getPreferences(): Collection
    {
        return $this->preferences;
    }

    /**
     * @param iterable<UserPreference> $preferences
     * @return User
     */
    public function setPreferences(iterable $preferences): User
    {
        $this->preferences = new ArrayCollection();

        foreach ($preferences as $preference) {
            $this->addPreference($preference);
        }

        return $this;
    }

    /**
     * @param string $name
     * @param bool|int|string|null $value
     */
    public function setPreferenceValue(string $name, $value = null)
    {
        $pref = $this->getPreference($name);

        if (null === $pref) {
            $pref = new UserPreference();
            $pref->setName($name);
            $this->addPreference($pref);
        }

        $pref->setValue($value);
    }

    public function getPreference(string $name): ?UserPreference
    {
        // this code will be triggered, if a currently logged-in user will be deleted and the refreshed from the session
        // via one of the UserProvider - e.g. see LdapUserProvider::refreshUser() which calls $user->getPreferenceValue()
        if (empty($this->preferences)) {
            return null;
        }

        foreach ($this->preferences as $preference) {
            if ($preference->getName() == $name) {
                return $preference;
            }
        }

        return null;
    }

    public function getLocale(): string
    {
        return $this->getPreferenceValue(UserPreference::LOCALE, User::DEFAULT_LANGUAGE);
    }

    public function getTimezone(): string
    {
        return $this->getPreferenceValue(UserPreference::TIMEZONE, date_default_timezone_get());
    }

    /**
     * @param string $name
     * @param mixed $default
     * @return bool|int|null|string
     */
    public function getPreferenceValue($name, $default = null)
    {
        $preference = $this->getPreference($name);
        if (null === $preference) {
            return $default;
        }

        return $preference->getValue();
    }

    /**
     * @param UserPreference $preference
     * @return User
     */
    public function addPreference(UserPreference $preference): User
    {
        $this->preferences->add($preference);
        $preference->setUser($this);

        return $this;
    }

    public function addTeam(Team $team): User
    {
        if ($this->teams->contains($team)) {
            return $this;
        }

        $this->teams->add($team);
        $team->addUser($this);

        return $this;
    }

    public function removeTeam(Team $team)
    {
        if (!$this->teams->contains($team)) {
            return;
        }
        $this->teams->removeElement($team);
        $team->removeUser($this);
    }

    /**
     * @return Collection<Team>
     */
    public function getTeams(): Collection
    {
        return $this->teams;
    }

    public function isInTeam(Team $team): bool
    {
        return $this->teams->contains($team);
    }

    public function isTeamleadOf(Team $team): bool
    {
        return $team->getTeamLead() === $this;
    }

    public function isTeamlead(): bool
    {
        return $this->hasRole(static::ROLE_TEAMLEAD);
    }

    public function isAdmin(): bool
    {
        return $this->hasRole(static::ROLE_ADMIN);
    }

    public function getDisplayName(): ?string
    {
        if (!empty($this->getAlias())) {
            return $this->getAlias();
        }

        return $this->getUsername();
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->getDisplayName();
    }
}

templates/invoice/actions.html.twig
{% macro invoices(view) %}
    {% import "macros/widgets.html.twig" as widgets %}

    {% set actions = {'visibility': '#modal_invoice'} %}

    {% if is_granted('manage_invoice_template') %}
        {% set actions = actions|merge({'list': path('admin_invoice_template')}) %}
    {% endif %}

    {% set actions = actions|merge({'help': {'url': 'invoices.html'|docu_link, 'target': '_blank'}}) %}

    {% set event = trigger('actions.invoices', {'actions': actions, 'view': view}) %}
    {{ widgets.page_actions(event.payload.actions) }}
{% endmacro %}

{% macro invoice_templates(view) %}
    {% import "macros/widgets.html.twig" as widgets %}

    {% set actions = {} %}
    {% if is_granted('view_invoice') %}
        {% set actions = actions|merge({'back': path('invoice')}) %}
    {% endif %}

    {% if is_granted('manage_invoice_template') %}
        {% set actions = actions|merge({'create': path('admin_invoice_template_create')}) %}
    {% endif %}

    {% set actions = actions|merge({'help': {'url': 'invoices.html'|docu_link, 'target': '_blank'}}) %}

    {% set event = trigger('actions.invoice_templates', {'actions': actions, 'view': 'index'}) %}
    {{ widgets.page_actions(actions) }}
{% endmacro %}

{% macro invoice_template(template, view) %}
    {% import "macros/widgets.html.twig" as widgets %}

    {% set actions = {} %}
    
    {% if is_granted('manage_invoice_template') %}
        {% set actions = actions|merge({'edit': {'url': path('admin_invoice_template_edit', {'id' : template.id}), 'class': 'modal-ajax-form'}}) %}
        {% set actions = actions|merge({'copy': path('admin_invoice_template_copy', {'id' : template.id})}) %}
        {% set actions = actions|merge({'trash': path('admin_invoice_template_delete', {'id' : template.id})}) %}
    {% endif %}

    {% set event = trigger('actions.invoice_template', {'actions': actions, 'view': view, 'template': template}) %}
    {{ widgets.table_actions(event.payload.actions) }}
{% endmacro %}

templates/invoice/index.html.twig
{% extends 'base.html.twig' %}
{% import "macros/widgets.html.twig" as widgets %}
{% import "macros/toolbar.html.twig" as toolbar %}
{% import "macros/datatables.html.twig" as tables %}
{% import "invoice/actions.html.twig" as actions %}

{% set columns = {
    'date': 'alwaysVisible',
    'user': 'hidden-xs hidden-sm',
    'description': 'hidden-xs hidden-sm',
    'unit_price': 'hidden-xs text-center',
    'amount': 'text-center',
    'duration': 'hidden-xs text-center',
    'total_rate': 'text-right alwaysVisible',
} %}

{% set tableName = 'invoice' %}

{% block page_title %}{{ 'invoice.title'|trans }}{% endblock %}
{% block page_subtitle %}{{ 'invoice.subtitle'|trans }}{% endblock %}
{% block page_actions %}{{ actions.invoices('index') }}{% endblock %}

{% block main_before %}
    {{ tables.data_table_column_modal(tableName, columns) }}
{% endblock %}

{% block main %}

    {% if is_granted('create_invoice') %}
        {% embed '@AdminLTE/Widgets/box-widget.html.twig' %}
            {% form_theme form '@AdminLTE/layout/form-theme-horizontal.html.twig' %}
            {% block box_title %}{{ 'invoice.filter'|trans }}{% endblock %}
            {% block box_before %}{{ form_start(form) }}{% endblock %}
            {% block box_body %}
                {{ form_row(form.searchTerm) }}
                {{ form_row(form.daterange) }}
                {{ form_row(form.customer) }}
                {{ form_row(form.project) }}
                {{ form_row(form.activity) }}
                {{ form_row(form.users) }}
                {{ form_row(form.tags) }}
                {{ form_row(form.exported) }}
                {{ form_row(form.template) }}
                {{ form_row(form.markAsExported) }}
            {% endblock %}
            {% block box_footer%}
                {{ form_widget(form.create, {'attr': {'class': 'btn btn-success'}}) }}
                {{ form_widget(form.preview) }}
            {% endblock %}
            {% block box_after %}{{ form_end(form) }}{% endblock %}
        {% endembed %}
    {% else %}
        {{ widgets.callout('danger', 'http_error_403.suggestion'|trans({}, 'exceptions')) }}
    {% endif %}

    {% if preview %}
        {% if model.calculator is empty or model.calculator.entries is empty %}
            {{ widgets.callout('warning', 'error.no_entries_found') }}
        {% else %}
            {% set entries = model.calculator.entries %}
            {{ tables.data_table_header(tableName, columns) }}
            {% for entry in entries %}
                {% set amount = entry.amount %}
                {% set duration = entry.duration|duration_decimal ~ ' / ' ~ entry.duration|duration %}
                {% set rate = 0 %}
                {% if entry.fixedRate is not null %}
                    {% set rate = entry.fixedRate %}
                {% elseif entry.hourlyRate is not null %}
                    {% set rate = entry.hourlyRate %}
                {% endif %}
                <tr>
                    <td class="text-nowrap">{{ entry.begin|date_short }}</td>
                    <td class="{{ tables.data_table_column_class(tableName, columns, 'user') }}">{{ widgets.label_user(entry.user) }}</td>
                    <td class="{{ tables.data_table_column_class(tableName, columns, 'description') }} timesheet-description">
                        {% if entry.description is not empty %}
                            {{ entry.description|escape|desc2html }}
                        {% else %}
                            {{ entry.activity.name }} / {{ entry.project.name }}
                        {% endif %}
                    </td>
                    <td class="{{ tables.data_table_column_class(tableName, columns, 'unit_price') }} text-center">{{ rate|money(model.calculator.currency) }}</td>
                    <td class="{{ tables.data_table_column_class(tableName, columns, 'amount') }} text-center text-nowrap">{{ amount }}</td>
                    <td class="{{ tables.data_table_column_class(tableName, columns, 'duration') }} text-center text-nowrap">{{ duration }}</td>
                    <td class="text-right text-nowrap">{{ entry.rate|money(model.calculator.currency) }}</td>
                </tr>
            {% endfor %}
            {{ tables.data_table_footer(entries) }}
        {% endif %}
    {% endif %}

{% endblock %}

templates/invoice/layout.html.twig
<!DOCTYPE html>
<html lang="{{ app.request.locale }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    {{ encore_entry_link_tags('app') }}
    {{ encore_entry_script_tags('app') }}
</head>
<body class="invoice_print">
<div class="wrapper">
    <section class="invoice">
        {% block invoice %}{% endblock %}
    </section>
</div>
</body>
</html>

templates/invoice/template_edit.html.twig
{% extends app.request.xmlHttpRequest ? 'form.html.twig' : 'base.html.twig' %}

{% block page_title %}{{ 'admin_invoice_template.title'|trans }}{% endblock %}

{% block main %}
    {{ include(app.request.xmlHttpRequest ? 'default/_form_modal.html.twig' : 'default/_form.html.twig', {
        'title': template.name|default('create'|trans),
        'form': form,
        'back': path('admin_invoice_template')
    }) }}
{% endblock %}

templates/invoice/templates.html.twig
{% extends 'base.html.twig' %}
{% import "macros/widgets.html.twig" as widgets %}
{% import "macros/datatables.html.twig" as tables %}
{% import "invoice/actions.html.twig" as actions %}

{% block page_title %}{{ 'admin_invoice_template.title'|trans }}{% endblock %}
{% block page_actions %}{{ actions.invoice_templates('index') }}{% endblock %}

{% block main %}
    {% if entries.count == 0 %}
        {{ widgets.callout('warning', 'error.no_entries_found') }}
    {% endif %}

    {% set columns = {
        'name': 'alwaysVisible',
        'title': 'hidden-xs',
        'due_days': 'hidden-xs hidden-sm',
        'vat': 'hidden-xs hidden-sm',
        'actions': 'actions alwaysVisible',
    } %}

    {% set tableName = 'invoice_template' %}

    {{ tables.data_table_header(tableName, columns) }}

    {% for entry in entries %}
        <tr class="modal-ajax-form open-edit" data-href="{{ path('admin_invoice_template_edit', {'id' : entry.id}) }}">
            <td>{{ entry.name }}</td>
            <td class="{{ tables.data_table_column_class(tableName, columns, 'title') }}">{{ entry.title }}</td>
            <td class="{{ tables.data_table_column_class(tableName, columns, 'due_days') }}">{{ entry.dueDays }}</td>
            <td class="{{ tables.data_table_column_class(tableName, columns, 'vat') }}">{{ entry.vat }}</td>
            <td class="actions">
                {{- actions.invoice_template(entry, 'index') -}}
            </td>
        </tr>
    {% endfor %}

    {{ tables.data_table_footer(entries, 'admin_invoice_template') }}
{% endblock %}