src/Entity/Customer.php
<?php

/*
 * This file is part of the Kimai time-tracking app.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="kimai2_customers",
 *     indexes={
 *          @ORM\Index(columns={"visible"})
 *     }
 * )
 * @ORM\Entity(repositoryClass="App\Repository\CustomerRepository")
 *
 * columns={"visible"}  => IDX_5A9760447AB0E859 => used in customer dropdown
 */
class Customer implements EntityWithMetaFields
{
    public const DEFAULT_CURRENCY = 'EUR';

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * Do not increase length to more than 190 chars, otherwise "Index column size too large." will be triggered.
     *
     * @ORM\Column(name="name", type="string", length=150, nullable=false)
     * @Assert\NotBlank()
     * @Assert\Length(min=2, max=150)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="number", type="string", length=50, nullable=true)
     * @Assert\Length(max=50)
     */
    private $number;

    /**
     * @var string
     *
     * @ORM\Column(name="comment", type="text", nullable=true)
     */
    private $comment;

    /**
     * @var bool
     *
     * @ORM\Column(name="visible", type="boolean", nullable=false)
     * @Assert\NotNull()
     */
    private $visible = true;

    /**
     * @var string
     *
     * @ORM\Column(name="company", type="string", length=255, nullable=true)
     * @Assert\Length(max=255)
     */
    private $company;

    /**
     * @var string
     *
     * @ORM\Column(name="contact", type="string", length=255, nullable=true)
     * @Assert\Length(max=255)
     */
    private $contact;

    /**
     * @var string
     *
     * @ORM\Column(name="address", type="text", nullable=true)
     */
    private $address;

    /**
     * @var string
     *
     * @ORM\Column(name="country", type="string", length=2, nullable=false)
     * @Assert\NotBlank()
     * @Assert\Length(max=2)
     */
    private $country;

    /**
     * @var string
     *
     * @ORM\Column(name="currency", type="string", length=3, nullable=false)
     * @Assert\NotBlank()
     * @Assert\Length(max=3)
     */
    private $currency = self::DEFAULT_CURRENCY;

    /**
     * @var string
     *
     * @ORM\Column(name="phone", type="string", length=255, nullable=true)
     * @Assert\Length(max=255)
     */
    private $phone;

    /**
     * @var string
     *
     * @ORM\Column(name="fax", type="string", length=255, nullable=true)
     * @Assert\Length(max=255)
     */
    private $fax;

    /**
     * @var string
     *
     * @ORM\Column(name="mobile", type="string", length=255, nullable=true)
     * @Assert\Length(max=255)
     */
    private $mobile;

    /**
     * @var string
     *
     * Limited via RFC to 254 chars
     *
     * @ORM\Column(name="email", type="string", length=255, nullable=true)
     * @Assert\Length(max=254)
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="homepage", type="string", length=255, nullable=true)
     * @Assert\Length(max=255)
     */
    private $homepage;

    /**
     * @var string
     *
     * Length was determined by a MySQL column via "use mysql;describe time_zone_name;"
     *
     * @ORM\Column(name="timezone", type="string", length=64, nullable=false)
     * @Assert\NotBlank()
     * @Assert\Length(max=64)
     */
    private $timezone;

    // keep the trait include exactly here, for placing the column at the correct position
    use RatesTrait;
    use ColorTrait;
    use BudgetTrait;

    /**
     * @var CustomerMeta[]|Collection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\CustomerMeta", mappedBy="customer", cascade={"persist"})
     */
    private $meta;

    /**
     * @var Team[]|ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Team", cascade={"persist"}, inversedBy="customers")
     * @ORM\JoinTable(
     *  name="kimai2_customers_teams",
     *  joinColumns={
     *      @ORM\JoinColumn(name="customer_id", referencedColumnName="id", onDelete="CASCADE")
     *  },
     *  inverseJoinColumns={
     *      @ORM\JoinColumn(name="team_id", referencedColumnName="id", onDelete="CASCADE")
     *  }
     * )
     */
    private $teams;

    public function __construct()
    {
        $this->meta = new ArrayCollection();
        $this->teams = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setName(string $name): Customer
    {
        $this->name = $name;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setNumber(?string $number): Customer
    {
        $this->number = $number;

        return $this;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setComment(?string $comment): Customer
    {
        $this->comment = $comment;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setVisible(bool $visible): Customer
    {
        $this->visible = $visible;

        return $this;
    }

    public function isVisible(): bool
    {
        return $this->visible;
    }

    /**
     * @deprecated since 1.4
     */
    public function getVisible(): bool
    {
        return $this->visible;
    }

    public function setCompany(?string $company): Customer
    {
        $this->company = $company;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setContact(?string $contact): Customer
    {
        $this->contact = $contact;

        return $this;
    }

    public function getContact(): ?string
    {
        return $this->contact;
    }

    public function setAddress(?string $address): Customer
    {
        $this->address = $address;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setCountry(string $country): Customer
    {
        $this->country = $country;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCurrency(string $currency): Customer
    {
        $this->currency = $currency;

        return $this;
    }

    public function getCurrency(): string
    {
        return $this->currency;
    }

    public function setPhone(?string $phone): Customer
    {
        $this->phone = $phone;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setFax(?string $fax): Customer
    {
        $this->fax = $fax;

        return $this;
    }

    public function getFax(): ?string
    {
        return $this->fax;
    }

    public function setMobile(?string $mobile): Customer
    {
        $this->mobile = $mobile;

        return $this;
    }

    public function getMobile(): ?string
    {
        return $this->mobile;
    }

    public function setEmail(?string $mail): Customer
    {
        $this->email = $mail;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setHomepage(?string $homepage): Customer
    {
        $this->homepage = $homepage;

        return $this;
    }

    public function getHomepage(): ?string
    {
        return $this->homepage;
    }

    public function setTimezone(string $timezone): Customer
    {
        $this->timezone = $timezone;

        return $this;
    }

    public function getTimezone(): ?string
    {
        return $this->timezone;
    }

    /**
     * @internal only here for symfony forms
     * @return Collection|MetaTableTypeInterface[]
     */
    public function getMetaFields(): Collection
    {
        return $this->meta;
    }

    /**
     * @return MetaTableTypeInterface[]
     */
    public function getVisibleMetaFields(): array
    {
        $all = [];
        foreach ($this->meta as $meta) {
            if ($meta->isVisible()) {
                $all[] = $meta;
            }
        }

        return $all;
    }

    public function getMetaField(string $name): ?MetaTableTypeInterface
    {
        foreach ($this->meta as $field) {
            if (strtolower($field->getName()) === strtolower($name)) {
                return $field;
            }
        }

        return null;
    }

    public function setMetaField(MetaTableTypeInterface $meta): EntityWithMetaFields
    {
        if (null === ($current = $this->getMetaField($meta->getName()))) {
            $meta->setEntity($this);
            $this->meta->add($meta);

            return $this;
        }

        $current->merge($meta);

        return $this;
    }

    public function addTeam(Team $team)
    {
        if ($this->teams->contains($team)) {
            return $this;
        }

        $this->teams->add($team);
        $team->addCustomer($this);
    }

    public function removeTeam(Team $team)
    {
        if (!$this->teams->contains($team)) {

src/Form/Type/CustomerType.php
<?php

/*
 * This file is part of the Kimai time-tracking app.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Form\Type;

use App\Entity\Customer;
use App\Repository\CustomerRepository;
use App\Repository\Query\CustomerFormTypeQuery;
use App\Repository\Query\ProjectQuery;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Custom form field type to select a customer.
 */
class CustomerType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            // documentation is for NelmioApiDocBundle
            'documentation' => [
                'type' => 'integer',
                'description' => 'Customer ID',
            ],
            'label' => 'label.customer',
            'class' => Customer::class,
            'choice_label' => 'name',
            'query_builder_for_user' => true,
            'project_enabled' => false,
            'project_visibility' => ProjectQuery::SHOW_VISIBLE,
        ]);

        $resolver->setDefault('query_builder', function (Options $options) {
            return function (CustomerRepository $repo) use ($options) {
                $query = new CustomerFormTypeQuery();
                if (true === $options['query_builder_for_user']) {
                    $query->setUser($options['user']);
                }

                return $repo->getQueryBuilderForFormType($query);
            };
        });

        $resolver->setDefault('api_data', function (Options $options) {
            if (true === $options['project_enabled']) {
                return [
                    'select' => 'project',
                    'route' => 'get_projects',
                    'route_params' => ['customer' => '-s-', 'visible' => $options['project_visibility']],
                    'empty_route_params' => ['visible' => $options['project_visibility']],
                ];
            }

            return [];
        });
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return EntityType::class;
    }
}

templates/customer/actions.html.twig
{% macro customers(view) %}
    {% import "macros/widgets.html.twig" as widgets %}

    {% set actions = {'search': {'class': 'search-toggle visible-xs-inline'}, 'visibility': '#modal_customer_admin'} %}

    {% if is_granted('create_customer') %}
        {% set actions = actions|merge({'create': path('admin_customer_create')}) %}
    {% endif %}

    {% set actions = actions|merge({'help': {'url': 'customer.html'|docu_link, 'target': '_blank'}}) %}

    {% set event = trigger('actions.customers', {'actions': actions, 'view': view}) %}
    {{ widgets.page_actions(event.payload.actions) }}
{% endmacro %}

{% macro customer(customer, view) %}
    {% import "macros/widgets.html.twig" as widgets %}
    {% set actions = {} %}

    {% if customer.id is not empty %}
        {% if is_granted('edit', customer) %}
            {% set class = '' %}
            {% if view != 'edit' %}
                {% set class = 'modal-ajax-form' %}
            {% endif %}
            {% set actions = actions|merge({'edit': {'url': path('admin_customer_edit', {'id': customer.id}), 'class': class}}) %}
        {% endif %}
        {% if is_granted('budget', customer) %}
            {% set actions = actions|merge({'report': {'url': path('admin_customer_budget', {'id': customer.id})}}) %}
        {% endif %}
        {% if is_granted('permissions', customer) %}
            {% set actions = actions|merge({'permissions': {'url': path('admin_customer_permissions', {'id': customer.id})}}) %}
        {% endif %}
        {% if is_granted('view_project') %}
            {% set actions = actions|merge({'project': path('admin_project', {'customer': customer.id})}) %}
        {% endif %}
        {% if is_granted('view_activity') %}
            {% set actions = actions|merge({'activity': path('admin_activity', {'customer': customer.id})}) %}
        {% endif %}
        {% if is_granted('view_other_timesheet') %}
            {% set actions = actions|merge({'timesheet': path('admin_timesheet', {'customer': customer.id})}) %}
        {% endif %}
        {% if customer.visible and is_granted('create_project') %}
            {% set actions = actions|merge({'create-project': path('admin_project_create_with_customer', {'customer': customer.id})}) %}
        {% endif %}
        {% if view == 'index' and is_granted('delete', customer) %}
            {% set actions = actions|merge({'trash': {'url': path('admin_customer_delete', {'id': customer.id}), 'class': 'modal-ajax-form'}}) %}
        {% endif %}
    {% endif %}

    {% if view != 'index' %}
        {% set actions = actions|merge({'back': path('admin_customer')}) %}
    {% endif %}

    {% set event = trigger('actions.customer', {'actions': actions, 'view': view, 'customer': customer}) %}
    {% if view == 'index' %}
        {{ widgets.table_actions(event.payload.actions) }}
    {% else %}
        {{ widgets.entity_actions(event.payload.actions) }}
    {% endif %}
{% endmacro %}

templates/customer/budget.html.twig
{% extends 'base.html.twig' %}
{% import "customer/actions.html.twig" as actions %}

{% block page_title %}{{ 'admin_customer.title'|trans }}{% endblock %}
{% block page_actions %}{{ actions.customer(customer, 'delete') }}{% endblock %}

{% block main %}

    {% set params = {
        '%activity%': '<strong>' ~ stats.activityAmount ~ '</strong>',
        '%project%': '<strong>' ~ stats.projectAmount ~ '</strong>',
        '%customer%': '<strong>' ~ customer.name ~ '</strong>',
        '%records%': '<strong>' ~ stats.recordAmount ~ '</strong>',
        '%duration%': '<strong>' ~ stats.recordDuration|duration ~ '</strong>',
        '%rate%': '<strong>' ~ stats.recordRate|money ~ '</strong>'
    } %}

    {% embed '@AdminLTE/Widgets/box-widget.html.twig' %}
        {% import "macros/progressbar.html.twig" as progress %}
        {% block box_title %}{{ customer.name }}{% endblock %}
        {% block box_body %}
            <p>
                {{ 'admin_customer.short_stats'|trans(params)|raw }}
            </p>

            {{ progress.progressbar(customer.budget, stats.recordRate, 'label.budget'|trans, stats.recordRate|money(customer.currency) ~ ' / ' ~ customer.budget|money(customer.currency) ) }}
            {{ progress.progressbar(customer.timeBudget, stats.recordDuration, 'label.timeBudget'|trans, stats.recordDuration|duration ~ ' / ' ~ customer.timeBudget|duration ) }}
        {% endblock %}
    {% endembed %}

{% endblock %}

templates/customer/delete.html.twig
{% extends app.request.xmlHttpRequest ? 'form.html.twig' : 'base.html.twig' %}
{% import "customer/actions.html.twig" as actions %}

{% block page_title %}{{ 'admin_customer.title'|trans }}{% endblock %}
{% block page_actions %}{{ actions.customer(customer, 'delete') }}{% endblock %}

{% block main %}

    {% set inUse = (stats.recordAmount > 0) %}

    {% set params = {
        '%activity%': '<strong>' ~ stats.activityAmount ~ '</strong>',
        '%project%': '<strong>' ~ stats.projectAmount ~ '</strong>',
        '%customer%': '<strong>' ~ customer.name ~ '</strong>',
        '%records%': '<strong>' ~ stats.recordAmount ~ '</strong>',
        '%duration%': '<strong>' ~ stats.recordDuration|duration ~ '</strong>'
    } %}

    {% set message = '<p>' ~ ("admin_customer.short_stats"|trans(params)|raw) ~ '</p><p>' ~ ("admin_entity.delete_confirm"|trans|raw) ~ '</p>' %}

    {{ include(app.request.xmlHttpRequest ? 'default/_form_delete_modal.html.twig' : 'default/_form_delete.html.twig', {
        'message': message|raw,
        'form': form,
        'used': inUse,
        'back': path('admin_customer')
    }) }}

{% endblock %}

templates/customer/edit.html.twig
{% extends app.request.xmlHttpRequest ? 'form.html.twig' : 'base.html.twig' %}
{% import "macros/widgets.html.twig" as widgets %}
{% import "customer/actions.html.twig" as actions %}

{% block page_title %}{{ 'admin_customer.title'|trans }}{% endblock %}
{% block page_actions %}{{ actions.customer(customer, 'edit') }}{% endblock %}

{% block main %}
    {% set formEditTemplate = app.request.xmlHttpRequest ? 'default/_form_modal.html.twig' : 'default/_form.html.twig' %}
    {% set formOptions = {
        'title': customer.name|default('create'|trans),
        'form': form,
        'back': path('admin_customer')
    } %}
    {% embed formEditTemplate with formOptions %}
        {% block form_body %}
            <div class="row">
                <div class="col-md-10">
                    {{ form_row(form.name) }}
                </div>
                <div class="col-md-2">
                    {{ form_row(form.color) }}
                </div>
            </div>
            {{ form_row(form.comment) }}
            <fieldset>
                {#<legend>Company data</legend>#}
                {{ form_row(form.company) }}
                {{ form_row(form.address) }}
                <div class="row">
                    <div class="col-md-4">
                        {{ form_row(form.country) }}
                    </div>
                    <div class="col-md-4">
                        {{ form_row(form.currency) }}
                    </div>
                    <div class="col-md-4">
                        {{ form_row(form.timezone) }}
                    </div>
                </div>
            </fieldset>
            <fieldset>
                {#<legend>Contact data</legend>#}
                <div class="row">
                    <div class="col-md-4">
                        {{ form_row(form.contact) }}
                    </div>
                    <div class="col-md-4">
                        {{ form_row(form.email) }}
                    </div>
                    <div class="col-md-4">
                        {{ form_row(form.homepage) }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        {{ form_row(form.mobile) }}
                    </div>
                    <div class="col-md-4">
                        {{ form_row(form.phone) }}
                    </div>
                    <div class="col-md-4">
                        {{ form_row(form.fax) }}
                    </div>
                </div>
            </fieldset>
            <fieldset>
                {#<legend>Financial data</legend>#}
                <div class="row">
                    <div class="col-md-6">
                        {{ form_row(form.fixedRate) }}
                    </div>
                    <div class="col-md-6">
                        {{ form_row(form.hourlyRate) }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        {{ form_row(form.budget) }}
                    </div>
                    <div class="col-md-6">
                        {{ form_row(form.timeBudget) }}
                    </div>
                </div>
            </fieldset>
            {{ form_row(form.visible) }}
            {% if form.metaFields is defined and form.metaFields is not empty %}
                <fieldset>
                    {#<legend>Custom fields</legend>#}
                    {{ form_row(form.metaFields) }}
                </fieldset>
            {% endif %}
            {{ form_widget(form) }}
        {% endblock %}
    {% endembed %}
{% endblock %}

templates/customer/index.html.twig
{% extends 'base.html.twig' %}
{% import "macros/widgets.html.twig" as widgets %}
{% import "macros/datatables.html.twig" as tables %}
{% import "macros/toolbar.html.twig" as toolbar %}
{% import "customer/actions.html.twig" as actions %}

{% set columns = {
    'name': 'alwaysVisible',
    'comment': 'hidden-xs',
    'country': 'hidden-xs hidden-sm',
    'number': 'hidden-xs',
} %}
{% for field in metaColumns %}
    {% set columns = columns|merge({
        ('mf_' ~ field.name): {'title': field.label, 'class': 'hidden-xs hidden-sm', 'orderBy': false}
    }) %}
{% endfor %}
{% set columns = columns|merge({
    'email': {'class': 'text-center hidden hidden-xs', 'orderBy': false},
    'homepage': {'class': 'text-center hidden hidden-xs', 'orderBy': false},
    'mobile': {'class': 'text-center hidden hidden-xs', 'orderBy': false},
    'phone': {'class': 'text-center hidden hidden-xs', 'orderBy': false},
    'team': {'class': 'text-center', 'orderBy': false},
    'visible': {'class': 'text-center', 'orderBy': false},
    'actions': 'actions alwaysVisible',
}) %}

{% set tableName = 'customer_admin' %}

{% block page_title %}{{ 'admin_customer.title'|trans }}{% endblock %}
{% block page_search %}{{ toolbar.dropDownSearch(toolbarForm) }}{% endblock %}
{% block page_actions %}{{ actions.customers('index') }}{% endblock %}

{% block main_before %}
    {{ tables.data_table_column_modal(tableName, columns) }}
{% endblock %}

{% block main %}

    {% if entries.count == 0 %}
        {{ widgets.callout('warning', 'error.no_entries_found') }}
    {% else %}
        {{ tables.datatable_header(tableName, columns, query, {'reload': 'kimai.customerUpdate'}) }}

        {% for entry in entries %}
            <tr{% if is_granted('edit', entry) %} class="modal-ajax-form open-edit" data-href="{{ path('admin_customer_edit', {'id': entry.id}) }}"{% endif %}>
                <td>{{ widgets.label_color_dot('customer', true, entry.name, null, entry.color) }} {% if entry.company is not empty %}({{ entry.company }}){% endif %}</td>
                <td class="{{ tables.data_table_column_class(tableName, columns, 'comment') }}">{{ entry.comment|comment2html }}</td>
                <td class="{{ tables.data_table_column_class(tableName, columns, 'country') }}">{{ entry.country|country }}</td>
                <td class="{{ tables.data_table_column_class(tableName, columns, 'number') }}">{{ entry.number }}</td>
                {% for field in metaColumns %}
                    <td class="text-nowrap {{ tables.data_table_column_class(tableName, columns, 'mf_' ~ field.name) }}">
                        {{ tables.datatable_meta_column(entry, field) }}
                    </td>
                {% endfor %}
                <td class="{{ tables.data_table_column_class(tableName, columns, 'email') }}">
                    {% if entry.email is not empty %}
                        <a href="mailto:{{ entry.email }}"><i class="{{ 'mail'|icon }}"></i></a>
                    {% else %}
                        &ndash;
                    {% endif %}
                </td>
                <td class="{{ tables.data_table_column_class(tableName, columns, 'homepage') }}">
                    {% if entry.homepage is not empty %}
                        <a href="{{ entry.homepage }}" target="_blank"><i class="{{ 'home'|icon }}"></i></a>
                    {% else %}
                        &ndash;
                    {% endif %}
                </td>
                <td class="{{ tables.data_table_column_class(tableName, columns, 'mobile') }}">
                    {% if entry.mobile is not empty %}
                        <a href="tel:{{ entry.mobile }}"><i class="{{ 'mobile'|icon }}"></i></a>
                    {% else %}
                        &ndash;
                    {% endif %}
                </td>
                <td class="{{ tables.data_table_column_class(tableName, columns, 'phone') }}">
                    {% if entry.phone is not empty %}
                        <a href="tel:{{ entry.phone }}"><i class="{{ 'phone'|icon }}"></i></a>
                    {% else %}
                        &ndash;
                    {% endif %}
                </td>
                <td class="{{ tables.data_table_column_class(tableName, columns, 'team') }}">
                    {% if entry.teams|length > 0 %}
                        {{ widgets.badge_counter(entry.teams|length) }}
                    {% else %}
                        {{ widgets.icon('unlocked') }}
                    {% endif %}
                </td>
                <td class="{{ tables.data_table_column_class(tableName, columns, 'visible') }}">{{ widgets.label_visible(entry.visible) }}</td>
                <td class="actions">
                    {{ actions.customer(entry, 'index') }}
                </td>
            </tr>
        {% endfor %}

        {{ tables.data_table_footer(entries, 'admin_customer_paginated') }}
    {% endif %}

{% endblock %}

templates/customer/permissions.html.twig
{% extends app.request.xmlHttpRequest ? 'form.html.twig' : 'base.html.twig' %}
{% import "macros/widgets.html.twig" as widgets %}
{% import "customer/actions.html.twig" as actions %}

{% block page_title %}{{ 'admin_customer.title'|trans }}{% endblock %}
{% block page_actions %}{{ actions.customer(customer, 'permissions') }}{% endblock %}

{% block main %}
    {{ include(app.request.xmlHttpRequest ? 'default/_form_modal.html.twig' : 'default/_form.html.twig', {
        'title': customer.name,
        'form': form,
        'back': path('admin_customer')
    }) }}
{% endblock %}