src/Entity/User.php
<?php

/*
 * This file is part of the Kimai time-tracking app.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="kimai2_users",
 *      uniqueConstraints={
 *          @ORM\UniqueConstraint(columns={"username"}),
 *          @ORM\UniqueConstraint(columns={"email"})
 *      }
 * )
 * @UniqueEntity("username")
 * @UniqueEntity("email")
 */
class User extends BaseUser implements UserInterface
{
    public const ROLE_USER = 'ROLE_USER';
    public const ROLE_TEAMLEAD = 'ROLE_TEAMLEAD';
    public const ROLE_ADMIN = 'ROLE_ADMIN';
    public const ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN';

    public const DEFAULT_ROLE = self::ROLE_USER;
    public const DEFAULT_LANGUAGE = 'en';

    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(name="id", type="integer")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="alias", type="string", length=60, nullable=true)
     * @Assert\Length(max=160)
     */
    private $alias;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="registration_date", type="datetime", nullable=true)
     */
    private $registeredAt;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=50, nullable=true)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="avatar", type="string", length=255, nullable=true)
     */
    private $avatar;

    /**
     * @var string
     *
     * @ORM\Column(name="api_token", type="string", length=255, nullable=true)
     */
    protected $apiToken;

    /**
     * @var string
     */
    protected $plainApiToken;

    /**
     * @var UserPreference[]|Collection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\UserPreference", mappedBy="user", cascade={"persist"})
     */
    private $preferences;

    /**
     * @var Team[]|ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Team", inversedBy="users", cascade={"persist"})
     * @ORM\JoinTable(
     *  name="kimai2_users_teams",
     *  joinColumns={
     *      @ORM\JoinColumn(name="user_id", referencedColumnName="id", onDelete="CASCADE")
     *  },
     *  inverseJoinColumns={
     *      @ORM\JoinColumn(name="team_id", referencedColumnName="id", onDelete="CASCADE")
     *  }
     * )
     */
    private $teams;

    /**
     * User constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->registeredAt = new \DateTime();
        $this->preferences = new ArrayCollection();
        $this->teams = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRegisteredAt(): ?\DateTime
    {
        return $this->registeredAt;
    }

    public function setRegisteredAt(\DateTime $registeredAt): User
    {
        $this->registeredAt = $registeredAt;

        return $this;
    }

    public function setAlias(?string $alias): User
    {
        $this->alias = $alias;

        return $this;
    }

    public function getAlias(): ?string
    {
        return $this->alias;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): User
    {
        $this->title = $title;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): User
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getApiToken(): ?string
    {
        return $this->apiToken;
    }

    public function setApiToken(?string $apiToken): User
    {
        $this->apiToken = $apiToken;

        return $this;
    }

    public function getPlainApiToken(): ?string
    {
        return $this->plainApiToken;
    }

    public function setPlainApiToken(?string $plainApiToken): User
    {
        $this->plainApiToken = $plainApiToken;

        return $this;
    }

    /**
     * @return Collection<UserPreference>
     */
    public function getPreferences(): Collection
    {
        return $this->preferences;
    }

    /**
     * @param iterable<UserPreference> $preferences
     * @return User
     */
    public function setPreferences(iterable $preferences): User
    {
        $this->preferences = new ArrayCollection();

        foreach ($preferences as $preference) {
            $this->addPreference($preference);
        }

        return $this;
    }

    /**
     * @param string $name
     * @param bool|int|string|null $value
     */
    public function setPreferenceValue(string $name, $value = null)
    {
        $pref = $this->getPreference($name);

        if (null === $pref) {
            $pref = new UserPreference();
            $pref->setName($name);
            $this->addPreference($pref);
        }

        $pref->setValue($value);
    }

    public function getPreference(string $name): ?UserPreference
    {
        // this code will be triggered, if a currently logged-in user will be deleted and the refreshed from the session
        // via one of the UserProvider - e.g. see LdapUserProvider::refreshUser() which calls $user->getPreferenceValue()
        if (empty($this->preferences)) {
            return null;
        }

        foreach ($this->preferences as $preference) {
            if ($preference->getName() == $name) {
                return $preference;
            }
        }

        return null;
    }

    public function getLocale(): string
    {
        return $this->getPreferenceValue(UserPreference::LOCALE, User::DEFAULT_LANGUAGE);
    }

    public function getTimezone(): string
    {
        return $this->getPreferenceValue(UserPreference::TIMEZONE, date_default_timezone_get());
    }

    /**
     * @param string $name
     * @param mixed $default
     * @return bool|int|null|string
     */
    public function getPreferenceValue($name, $default = null)
    {
        $preference = $this->getPreference($name);
        if (null === $preference) {
            return $default;
        }

        return $preference->getValue();
    }

    /**
     * @param UserPreference $preference
     * @return User
     */
    public function addPreference(UserPreference $preference): User
    {
        $this->preferences->add($preference);
        $preference->setUser($this);

        return $this;
    }

    public function addTeam(Team $team): User
    {
        if ($this->teams->contains($team)) {
            return $this;
        }

        $this->teams->add($team);
        $team->addUser($this);

        return $this;
    }

    public function removeTeam(Team $team)
    {
        if (!$this->teams->contains($team)) {
            return;
        }
        $this->teams->removeElement($team);
        $team->removeUser($this);
    }

    /**
     * @return Collection<Team>
     */
    public function getTeams(): Collection
    {
        return $this->teams;
    }

    public function isInTeam(Team $team): bool
    {
        return $this->teams->contains($team);
    }

    public function isTeamleadOf(Team $team): bool
    {
        return $team->getTeamLead() === $this;
    }

    public function isTeamlead(): bool
    {
        return $this->hasRole(static::ROLE_TEAMLEAD);
    }

    public function isAdmin(): bool
    {
        return $this->hasRole(static::ROLE_ADMIN);
    }

    public function getDisplayName(): ?string
    {
        if (!empty($this->getAlias())) {
            return $this->getAlias();
        }

        return $this->getUsername();
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->getDisplayName();
    }
}

templates/macros/progressbar.html.twig
{% macro progressbar(max, current, title, subTitle) %}
    {% set percentReached = 0 %}
    {% if max > 0 %}
        {% set percentReached = (current / (max / 100)) %}
    {% endif %}
    {% set class = "progress-bar-info" %}
    {% set width = percentReached|number_format(1, '.', '') %}

    {% if percentReached > 90 %}
        {% set class = "progress-bar-danger" %}
    {% elseif percentReached > 70 %}
        {% set class = "progress-bar-warning" %}
    {% elseif percentReached > 50 %}
        {% set class = "progress-bar-success" %}
    {% elseif percentReached > 30 %}
        {% set class = "progress-bar-primary" %}
    {% endif %}

    {% if width > 100 %}
        {% set width = 100 %}
    {% endif %}

    <div class="progress-group">
        <span class="progress-text">{{ title }}{% if percentReached > 0 %} &ndash; {{ percentReached|number_format(2) }}%{% endif %}</span>
        <span class="progress-number">{{ subTitle }}</span>

        <div class="progress">
            <div class="progress-bar {{ class }}" role="progressbar" aria-valuenow="{{ width }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ width }}%"></div>
        </div>
    </div>
{% endmacro %}

{% macro progressbar_small(max, current, leftValue, leftFormatted) %}
    {% set percentReached = 0 %}
    {% if max > 0 %}
        {% set percentReached = (current / (max / 100)) %}
    {% endif %}
    {% set class = "progress-bar-info" %}
    {% set width = percentReached|number_format(1, '.', '') %}

    {% if percentReached > 90 %}
        {% set class = "progress-bar-danger" %}
    {% elseif percentReached > 70 %}
        {% set class = "progress-bar-warning" %}
    {% elseif percentReached > 50 %}
        {% set class = "progress-bar-success" %}
    {% elseif percentReached > 30 %}
        {% set class = "progress-bar-primary" %}
    {% endif %}

    {% if width > 100 %}
        {% set width = 100 %}
    {% endif %}

    <div class="progress-group">
        <div class="progress progress-sm">
            <div class="progress-bar {{ class }}" role="progressbar" aria-valuenow="{{ width }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ width }}%"></div>
        </div>
        {% if leftValue is not null and leftValue > 0 %}
            <small>{{ 'stats.percentUsedLeft'|trans({'%percent%': percentReached|number_format(0), '%left%': leftFormatted}) }}</small>
        {% else %}
            <small>{{ 'stats.percentUsed'|trans({'%percent%': percentReached|number_format(0)}) }}</small>
        {% endif %}
    </div>
{% endmacro %}

templates/macros/toolbar.html.twig
{% macro toolbar(form, collapsible, displayInitial) %}
    {% deprecated 'The macro "toolbar" is deprecated since 1.2 and will be removed with 2.0, use dropDownSearch() instead' %}
    <div class="toolbar no-print">
        {% if collapsible %}<div class="collapse{% if displayInitial %} collapse.show in{% endif %}" id="{{ collapsible }}">{% endif %}
            {{ form_start(form, { 'attr': {'class': 'navbar-form'}}) }}
            {{ form_widget(form) }}
            {{ form_end(form) }}
        {% if collapsible %}</div>{% endif %}
    </div>
{% endmacro %}

{% macro dropDownSearch(form) %}
    {% form_theme form 'form/search-form.html.twig' %}
    {{ form_start(form, { 'attr': {'class': 'form-horizontal header-search hidden-xs'}}) }}
    {% set searchTermClass = 'dropdown-toggle input-sm' %}
    {% if not form.searchTerm.vars.valid %}
        {% set searchTermClass = searchTermClass ~ ' search-has-error' %}
    {% endif %}
    {% if not form.vars.valid %}
        {% set searchTermClass = searchTermClass ~ ' has-error' %}
    {% endif %}
    <div class="dropdown">
        <div class="form-group">
            <div class="input-group">
                <div class="input-group-addon {% if not form.vars.valid %} has-error{% endif %}">
                    <i class="{{ 'search'|icon }}"></i>
                </div>
                {{ form_widget(form.searchTerm, {'attr': {'placeholder': 'search'|trans, 'autocomplete': 'off', 'data-toggle': 'dropdown', 'class': searchTermClass, 'aria-haspopup': 'true', 'aria-expanded': 'true'}}) }}
                <ul class="dropdown-menu pre-scrollable" role="menu" aria-labelledby="searchTerm">
                    <li>
                        <div class="container-fluid">
                            {% if not form.searchTerm.vars.valid %}
                                {{ form_errors(form.searchTerm) }}
                                <br>
                            {% endif %}
                            {{ form_widget(form) }}
                            <div class="form-group">
                                <div class="col-sm-3 col-xs-4"></div>
                                <div class="col-sm-9 col-xs-8">
                                    {% if not theme_config('auto_reload_datatable') %}
                                        {# FIXME this should trigger the datatable reload and not "really" submit the form #}
                                    <input type="submit" value="{{ 'search'|trans }}" class="btn btn-primary" />
                                    {% endif %}
                                    <a href="#" class="search-cancel pull-right">{{ 'action.close'|trans }}</a>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    {{ form_end(form) }}
{% endmacro %}

templates/macros/widgets.html.twig
{% macro icon(icon) %}
<i class="{{ icon|icon(icon) }}"></i>
{% endmacro %}

{%- macro page_actions(tools) -%}
    {% import _self as macro %}
    <div class="breadcrumb">
        <div class="box-tools">
            {{ macro.button_group(tools) }}
        </div>
    </div>
{%- endmacro -%}

{%- macro entity_actions(tools) -%}
    {% import _self as macro %}
    <div class="breadcrumb">
        <div class="box-tools">
            {{ macro.table_actions(tools) }}
        </div>
    </div>
{%- endmacro -%}

{% macro page_header(title) %}
    <h2 class="page-header">{{ title|trans }}</h2>
{% endmacro %}

{% macro label_boolean(visible) %}
    {% import _self as macro %}
    {% if visible %}
        {{ macro.label('yes', 'success') }}
    {% else %}
        {{ macro.label('no', 'default') }}
    {% endif %}
{% endmacro %}

{% macro label_visible(visible) %}
    {% import _self as macro %}
    {{ macro.label_boolean(visible) }}
{% endmacro %}

{% macro label_role(role) %}
    {% import _self as macro %}
    {% if role == 'ROLE_SUPER_ADMIN' %}
        {{ macro.label(role, 'danger') }}
    {% elseif role == 'ROLE_ADMIN' %}
        {{ macro.label(role, 'warning') }}
    {% elseif role == 'ROLE_TEAMLEAD' %}
        {{ macro.label(role, 'success') }}
    {% elseif role == 'ROLE_USER' %}
        {{ macro.label(role, 'gray') }}
    {% else %}
        {{ macro.label(role, 'primary') }}
    {% endif %}
{% endmacro %}

{% macro username(user) %}
    {{- user.displayName -}}
{% endmacro %}

{% macro label_user(user) %}
    {% import _self as macro %}
    {{ macro.label(user.displayName, 'primary') }}
{% endmacro %}

{% macro label_team(team, class) %}
    {% import _self as macro %}
    {{ macro.label(team.name, class|default('primary')) }}
{% endmacro %}

{% macro user_avatar(user, tooltip) %}
    {% set avatar = avatar(user, admin_lte_context.default_avatar) %}
    {% set showTooltip = tooltip|default(true) %}
    {% if tooltip is not defined or tooltip is same as (false)%}
    <img src="{{ avatar }}" class="{{ class|default('img-circle') }}" alt="{{ user.displayName }}" />
    {% else %}
    <img src="{{ avatar }}" class="{{ class|default('img-circle') }}" data-toggle="tooltip" data-placement="top" alt="{{ user.displayName }}" title="{{ user.displayName }}" />
    {% endif %}
{% endmacro %}

{% macro label_activity(activity, url) %}
    {% import _self as macro %}
    {% set isVisible = activity.visible %}
    {% set color = activity.color %}
    {% if color is empty and activity.project is not null %}
        {% set color = activity.project.color ?? activity.project.customer.color %}
    {% endif %}
    {% if isVisible and not activity.project is null %}
        {% set isVisible = activity.project.visible %}
        {% if isVisible and not activity.project.customer is null %}
            {% set isVisible = activity.project.customer.visible %}
        {% endif %}
    {% endif %}
    {{ macro.label_color_dot('activity', isVisible, activity.name, url, color) }}
{% endmacro %}

{% macro label_project(project, url) %}
    {% import _self as macro %}
    {% set isVisible = false %}
    {% if project.visible and project.customer.visible %}
        {% set isVisible = true %}
    {% endif %}
    {{ macro.label_color_dot('project', isVisible, project.name, url, (project.color ?? project.customer.color)) }}
{% endmacro %}

{% macro label_customer(customer, url) %}
    {% import _self as macro %}
    {% set isVisible = customer.visible %}
    {{ macro.label_color_dot('customer', isVisible, customer.name, url, customer.color) }}
{% endmacro %}

{% macro label_color_dot(type, isVisible, name, url, color) %}
    <span class="label-{{ type }}{{ isVisible ? '' : ' label-invisible' }}">
        <span class="dot"{% if color is not empty %} style="background-color:{{ color }}"{% endif %}></span>
        <span class="name">
            {% if url is not empty %}
                <a href="{{ url }}">{{ name }}</a>
            {% else %}
                {{ name }}
            {% endif %}
        </span>
    </span>
{% endmacro %}

{% macro color_dot(color, tooltip) %}
    <span class="label-color" data-toggle="tooltip" data-placement="top" title="{{ tooltip }}">
        <span class="dot" style="background-color:{{ color }}"></span>
    </span>
{% endmacro %}

{% macro badge_counter(count, url) %}
    {% if url %}
        <a href="{{ url }}"><span class="badge bg-blue">{{ count }}</span></a>
    {% else %}
        <span class="badge bg-blue">{{ count }}</span>
    {% endif %}
{% endmacro %}

{% macro label(title, type, tooltip) %}
    {# success, warning, danger, primary #}
    <span {% if tooltip %}data-toggle="tooltip" data-placement="top" title="{{ tooltip }}" {% endif %}class="label label-{{ type|default('success') }}">{{ title|trans }}</span>
{% endmacro %}

{% macro badge(title, color) %}
    {# black, green, blue, yellow #}
    <span class="badge bg-{{ color|default('red') }}">{{ title|trans }}</span>
{% endmacro %}

{% macro alert(type, description, title, icon) %}
    <div class="alert alert-{{ type|default('danger') }} alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        {% if title and icon %}
            <h4><i class="icon {{ icon|icon(icon) }}"></i> {{ title|trans }}</h4>
            {{ description|trans }}
        {% elseif icon %}
            <h4><i class="icon {{ icon|icon(icon) }}"></i> {{ description|trans }}</h4>
        {% else %}
            {{ description|trans }}
        {% endif %}
    </div>
{% endmacro %}

{% macro callout(type, description, title, icon) %}
    <div class="callout callout-{{ type|default('danger') }} lead">
        {% if title %}<h4>{% if icon %}<i class="{{ icon|icon(icon) }}">{% endif %}</i> {{ title|trans }}</h4>{% endif %}
        <p>{{ description|trans }}</p>
    </div>
{% endmacro %}

{% macro info_box_progress(title, description, amount, percentage, icon, color) %}
    <div class="info-box bg-{{ color }}">
        <span class="info-box-icon"><i class="{{ icon|icon(icon) }}"></i></span>

        <div class="info-box-content">
            <span class="info-box-text">{{ title|trans }}</span>
            <span class="info-box-number">{{ amount }}</span>

            <div class="progress">
                <div class="progress-bar" style="width: {{ percentage }}%"></div>
            </div>
            <span class="progress-description">
                    {{ description }}
            </span>
        </div>
        <!-- /.info-box-content -->
    </div>
{% endmacro %}

{% macro button_group_dropdown(title, actions) %}
    <div class="btn-group">
        <button type="button" class="btn btn-default">{{ title|trans }}</button>
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <span class="caret"></span>
            <span class="sr-only">{{ 'label.toggle_dropdown'|trans }}</span>
        </button>
        <ul class="dropdown-menu" role="menu">
            {% for url, entry in actions %}
                <li><a href="{{ url }}">{{ entry|trans }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endmacro %}

{% macro table_actions(actions) %}
    {%- import _self as macro -%}
    {% if actions|length >= 1 %}
        <div class="btn-group">
            <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-expanded="false">{{ 'label.actions'|trans }}
                <span class="fa fa-caret-down"></span></button>
            <ul class="dropdown-menu dropdown-menu-right">
                {%- apply spaceless -%}
                    {%- for icon,values in actions  %}
                        {% set class = '' %}
                        {% if icon == 'trash' %}
                            {% set class = 'delete' %}
                            {% if actions|length > 1 %}
                            <li class="divider"></li>
                            {% endif %}
                        {% endif %}
                        <li class="{{ class }}">
                            {% if values is iterable %}
                                {{ macro.action_button(icon, values|merge({'title': icon|trans({}, 'actions')}), false) }}
                            {% else %}
                                {{ macro.action_button(icon, {'url': values, 'title': icon|trans({}, 'actions')}, false) }}
                            {% endif %}
                        </li>
                    {% endfor -%}
                {% endapply %}
            </ul>
        </div>
    {% endif %}
{% endmacro %}

{% macro action_button(icon, values, type) %}
    {%- import _self as macro -%}
    {%- apply spaceless -%}
        {% set id = null %}
        {% set onclick = null %}
        {% set modal = null %}
        {% set toggle = null %}
        {% set url = null %}
        {% set target = null %}
        {% set title = null %}
        {% set disabled = false %}
        {% set attr = {} %}
        {% if type is same as (false) %}
            {% set class = "" %}
        {% elseif type is null %}
            {% set class = "btn btn-default btn-" ~ icon ~ " " %}
        {% else %}
            {% set class = "btn btn-" ~ type ~ " btn-" ~ icon ~ " " %}
        {% endif %}

        {% if not values is iterable %}
            {% set url = values %}
            {% if 'onclick:' in url %}
                {% set onclick = url|replace({'onclick:': ''}) %}
                {% set url = '#' %}
            {% endif %}
            {% if '#collapse' in url %}
                {% set toggle = 'collapse' %}
            {% endif %}
            {% if '#modal' in url %}
                {% set modal = url %}
                {% set url = '#' %}
            {% endif %}
        {% else %}
            {% set disabled = values.disabled ?? false %}
            {% set url = values.url ?? '#' %}
            {% set onclick = values.onclick ?? null %}
            {% set modal = values.modal ?? null %}
            {% set toggle = values.toggle ?? null %}
            {% set target = values.target ?? null %}
            {% set id = values.id ?? null %}
            {% set title = values.title ?? null %}
            {% set class = class ~ ( values.class | default("")) %}
            {% set attr = values.attr ?? {} %}
        {% endif %}

        {% if disabled is same as (true) %}
            {% set class = class ~ " disabled"  %}
        {% endif %}

        <a class="{{ class | trim }}" href="{{ url }}"
                {%- if disabled is same as (true) %} disabled="disabled"{% endif %}
                {%- if id is not empty %} id="{{ id }}"{% endif %}
                {%- if toggle is not empty %} data-toggle="{{ toggle }}"{% endif %}
                {%- if modal is not empty %} data-toggle="modal" data-target="{{ modal }}"{% endif %}
                {%- if onclick is not empty %} onclick="{{ onclick }}"{% endif %}
                {%- if target is not empty %} target="{{ target }}"{% endif %}
                {%- if attr is not empty %}
                    {% for name, value in attr %}
                    {{ ' ' ~ name }}={% if '"' in value %}'{{ value|raw }}'{% else %}"{{ value|raw }}"{% endif %}
                    {% endfor %}
                {% endif %}
        >{% if title is not null %}{{ title }}{% else %}{{ macro.icon(icon) }}{% endif %}</a>
    {% endapply %}
{% endmacro %}

{% macro button_group(actions, type) %}
    {%- import _self as macro -%}
    <div class="btn-group">
        {%- apply spaceless -%}
        {%- for icon,values in actions  %}
            {{ macro.action_button(icon, values, type) }}
        {% endfor -%}
        {% endapply %}
    </div>
{% endmacro %}

{% macro button_action(icon, url) %}
    <a href="{{ url }}" class="btn btn-default btn-{{ icon }}">
        {{ macro.icon(icon) }}
    </a>
{% endmacro %}

{% macro tag_list(taglist) %}
    {% import _self as macro %}
    {% for tag in taglist %}
        {{ macro.badge(tag.name , 'green') }}
    {% endfor %}
{% endmacro %}

{% macro form_type_value(type, value, entity) %}
    {% import _self as widgets %}
    {% if '\\ColorPickerType' in type %}
        {{ widgets.color_dot(value, value) }}
    {% elseif '\\DurationType' in type %}
        {{ value|duration }}
    {% elseif '\\YesNoType' in type or '\\CheckBoxType' in type %}
        {{ widgets.label_boolean(value) }}
    {% elseif '\\DatePickerType' in type %}
        {{ value|date_short }}
    {% elseif '\\DateTimePickerType' in type %}
        {{ value|date_full }}
    {% elseif '\\CountryType' in type %}
        {{ value|country }}
    {% elseif '\\CurrencyType' in type %}
        {{ value|currency }}
    {% elseif '\\LanguageType' in type %}
        {{ value|language }}
    {% elseif '\\MoneyType' in type  %}
        {% if entity is null %}
            {{ value }}
        {% elseif class_name(entity) == 'App\\Entity\\Timesheet' %}
            {{ value|money(entity.project.customer.currency) }}
        {% elseif class_name(entity) == 'App\\Entity\\Customer' %}
            {{ value|money(entity.currency) }}
        {% elseif class_name(entity) == 'App\\Entity\\Project' %}
            {{ value|money(entity.customer.currency) }}
        {% elseif class_name(entity) == 'App\\Entity\\Activity' and entity.project is not null %}
            {{ value|money(entity.project.customer.currency) }}
        {% else %}
            {{ value }}
        {% endif %}
    {% else %}
        {{ value }}
    {% endif %}
{% endmacro %}